/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 2.8 */
/* D:\ProgramFiles64\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n bootROM -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 5 -num_rows 32 -data_width 8 -outdata UNREGISTERED -memfile v:/qv08_v5c/bootrom.mem -memformat orca  */
/* Wed Dec 11 05:54:01 2019 */


`timescale 1 ns / 1 ps
module bootROM (Address, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [4:0] Address;
    output wire [7:0] Q;


    defparam mem_0_7.initval =  32'h000375E0 ;
    ROM32X1A mem_0_7 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[7]));

    defparam mem_0_6.initval =  32'h000371D1 ;
    ROM32X1A mem_0_6 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[6]));

    defparam mem_0_5.initval =  32'h000334E1 ;
    ROM32X1A mem_0_5 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[5]));

    defparam mem_0_4.initval =  32'h000261A1 ;
    ROM32X1A mem_0_4 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[4]));

    defparam mem_0_3.initval =  32'h0001A9B5 ;
    ROM32X1A mem_0_3 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[3]));

    defparam mem_0_2.initval =  32'h00015545 ;
    ROM32X1A mem_0_2 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[2]));

    defparam mem_0_1.initval =  32'h00016184 ;
    ROM32X1A mem_0_1 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[1]));

    defparam mem_0_0.initval =  32'h0002B4D6 ;
    ROM32X1A mem_0_0 (.AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), 
        .AD1(Address[1]), .AD0(Address[0]), .DO0(Q[0]));



    // exemplar begin
    // exemplar end

endmodule
