/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.8.0.115.3 */
/* Module Version: 2.8 */
/* D:\ProgramFiles64\lscc\diamond\3.8_x64\ispfpga\bin\nt64\scuba.exe -w -n urom_TBL -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type rom -addr_width 8 -num_rows 256 -data_width 10 -outdata UNREGISTERED -memfile v:/qv08_v5c/urom/2908uromtbl.mem -memformat hex  */
/* Wed Dec 11 05:44:30 2019 */


`timescale 1 ns / 1 ps
module urom_TBL (Address, Q)/* synthesis NGD_DRC_MASK=1 */;
    input wire [7:0] Address;
    output wire [9:0] Q;


    defparam mem_0_9.initval = 256'hFFFFFFFFFFFFFFFFFFF800000000000000000000000000000000000000000000 ;
    ROM256X1A mem_0_9 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[9]));

    defparam mem_0_8.initval = 256'h00000000000000000007FFFFFFFFFFFFFFFFFE00000000000000000000000000 ;
    ROM256X1A mem_0_8 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[8]));

    defparam mem_0_7.initval = 256'hFFFFE000000000000007FFFFFFFFFC00000001FFFFFFFFFFFFFFFF0000000000 ;
    ROM256X1A mem_0_7 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[7]));

    defparam mem_0_6.initval = 256'hC0001FFFFFFFF8000007FFFFC00003FFFF0001FFFFFF0000000000FFFF000000 ;
    ROM256X1A mem_0_6 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[6]));

    defparam mem_0_5.initval = 256'h3F801FFE000007FFE007FE003FF003FF00FF01FF0000FFFFFFFF00FF00FF0000 ;
    ROM256X1A mem_0_5 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[5]));

    defparam mem_0_4.initval = 256'h387F9FF9FFE007F81F07C1F03E0F83E0E0E0E1E0FF80FFFF0000F0F0F0F0FF00 ;
    ROM256X1A mem_0_4 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[4]));

    defparam mem_0_3.initval = 256'hBE605801F01F878718C739CE318C639CDCDCDDDCFC70FF00FF00CCCCCCCCF0F0 ;
    ROM256X1A mem_0_3 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[3]));

    defparam mem_0_2.initval = 256'h645E4781CF1C6666D6B4A5AD294B5A5292B29B9EF34CF0F0F0F0AAAAAAAACCCC ;
    ROM256X1A mem_0_2 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[2]));

    defparam mem_0_1.initval = 256'hC539E6652CD355558CE673198CE6731939193532CA6ACCCCCCCC00000000AAAA ;
    ROM256X1A mem_0_1 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[1]));

    defparam mem_0_0.initval = 256'hB75575508A8A0000956A956A956A956AAA8AA0A8A0A0AAAAAAAA000000000000 ;
    ROM256X1A mem_0_0 (.AD7(Address[7]), .AD6(Address[6]), .AD5(Address[5]), 
        .AD4(Address[4]), .AD3(Address[3]), .AD2(Address[2]), .AD1(Address[1]), 
        .AD0(Address[0]), .DO0(Q[0]));



    // exemplar begin
    // exemplar end

endmodule
